# Generated by Django 3.2.5 on 2021-07-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='photo_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='album.photo'),
        ),
    ]
