# Generated by Django 3.2.5 on 2021-07-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_like_photo_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='photo_uuid',
            new_name='photo',
        ),
    ]
